# Generated by Django 2.2.2 on 2019-06-27 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=4096, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='PostReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Post')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Post reader list',
                'verbose_name_plural': 'Posts readers list',
                'ordering': ('pk',),
                'unique_together': {('post', 'reader')},
            },
        ),
    ]
