# Generated by Django 2.2.2 on 2019-06-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190627_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreader',
            options={'ordering': ('pk',), 'verbose_name': 'Post reader', 'verbose_name_plural': 'Posts readers'},
        ),
    ]
